name: Build & Release
on:
  push:
    tags: [ 'v*' ]
permissions:
  contents: write
jobs:
  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install deps
        run: brew install cmake
      - name: Fetch Steinberg VST3 SDK
        run: git clone --depth 1 https://github.com/steinbergmedia/vst3sdk external/vst3sdk
      - name: Configure (Universal)
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DVST3_SDK_DIR=${{ github.workspace }}/external/vst3sdk
      - name: Build
        run: cmake --build build --config Release --target ALL_BUILD --parallel
      - name: Package
        run: |
          mkdir -p dist
          zip -r "dist/CassetteInput-macOS-Universal-${GITHUB_REF_NAME}.zip" \
            build/CassetteInput_artefacts/Release/VST3/CassetteInput.vst3 \
            build/CassetteInput_artefacts/Release/AU/CassetteInput.component
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/CassetteInput-macOS-Universal-${{ github.ref_name }}.zip

  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Fetch Steinberg VST3 SDK
        run: git clone --depth 1 https://github.com/steinbergmedia/vst3sdk external/vst3sdk
      - name: Configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -A x64 -DVST3_SDK_DIR=$env:GITHUB_WORKSPACE\\external\\vst3sdk
      - name: Build
        run: cmake --build build --config Release --target ALL_BUILD -- /m
      - name: Package
        run: |
          mkdir dist
          powershell -Command "Compress-Archive -Path build\CassetteInput_artefacts\Release\VST3\CassetteInput.vst3 -DestinationPath dist\CassetteInput-Windows-x64-${{ github.ref_name }}.zip"
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist\CassetteInput-Windows-x64-${{ github.ref_name }}.zip
